# Generated by Django 2.1.3 on 2019-02-04 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0002_corpus_network_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ARNN.Template'),
            preserve_default=False,
        ),
    ]
