# Generated by Django 2.1.3 on 2019-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0004_auto_20190211_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
