# Generated by Django 2.1.3 on 2019-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0005_auto_20190213_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='seed',
            field=models.IntegerField(default=-1, verbose_name='Seed Aléatoire'),
        ),
    ]
