# Generated by Django 2.1.3 on 2019-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0006_template_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='corpus',
            name='data',
            field=models.FileField(default='Panda', max_length=300, upload_to=''),
        ),
        migrations.AddField(
            model_name='template',
            name='dim_output',
            field=models.IntegerField(default=1, verbose_name='Dimension of output'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='input_bias',
            field=models.BooleanField(default=True, verbose_name='Input bias'),
        ),
    ]
