# Generated by Django 2.1.3 on 2019-03-13 20:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ARNN', '0007_auto_20190312_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'Train'), ('2', 'Test')], max_length=1)),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starting step')),
                ('stop', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stopping step')),
            ],
            options={
                'ordering': ['creation_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('1', 'Train'), ('2', 'Test')], max_length=1)),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starting step')),
                ('stop', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stopping step')),
            ],
            options={
                'ordering': ['creation_date'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='data',
        ),
        migrations.AddField(
            model_name='corpus',
            name='data_in',
            field=models.FileField(default='Panda', max_length=500, upload_to=''),
        ),
        migrations.AddField(
            model_name='corpus',
            name='data_out',
            field=models.FileField(default='Panda', max_length=500, upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ARNN.Corpus'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observable',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ARNN.Corpus'),
        ),
        migrations.AddField(
            model_name='observable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
