# Generated by Django 2.1.3 on 2019-03-13 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0008_auto_20190313_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30000)),
            ],
        ),
        migrations.RemoveField(
            model_name='observable',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='start',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='observable',
            name='type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='corpus',
            name='data_name',
            field=models.CharField(default=None, max_length=30000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='dim_in',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='dim_out',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpus',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observable',
            name='kind_obs',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observable',
            name='periodicity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='periodicity'),
        ),
        migrations.AddField(
            model_name='task',
            name='kind_task',
            field=models.CharField(choices=[('Train', 'Train'), ('Test', 'Test')], default='Train', max_length=1),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='data_in',
            field=models.FileField(default='None', upload_to=''),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='data_out',
            field=models.FileField(default='None', upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starting step'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stop',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stopping step'),
        ),
    ]
