# Generated by Django 2.1.3 on 2019-03-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0009_auto_20190313_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observable',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Observable',
        ),
    ]
