# Generated by Django 2.1.3 on 2019-03-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0010_auto_20190318_2338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observables',
            new_name='Observable',
        ),
    ]
