# Generated by Django 2.1.7 on 2019-03-27 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0012_auto_20190319_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AddField(
            model_name='network',
            name='auto_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='N',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Reservoir Size'),
        ),
        migrations.AlterField(
            model_name='template',
            name='dim_input',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dimension of input'),
        ),
        migrations.AlterField(
            model_name='template',
            name='dim_output',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dimension of output'),
        ),
        migrations.AlterField(
            model_name='template',
            name='proba',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Probability of a connection'),
        ),
        migrations.AlterField(
            model_name='template',
            name='spectral_radius',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Spectral radius'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
