# Generated by Django 2.1.7 on 2019-03-27 18:01

from django.db import migrations

def populate_observables(apps, schema_editor):
    Observable = apps.get_model('ARNN', 'Observable')
    Observable.objects.filter(name="Normalized Root-Mean-Squarred Error"). delete()
    new = Observable(name='Rmse')
    new.save()
    new = Observable(name="Mse")
    new.save()
    new = Observable(name="Nmrse maxmin")
    new.save()
    new = Observable(name="Nmrse mean")
    new.save()
    new = Observable(name="Predicted Output")
    new.save()
    new = Observable(name="Expected Output")
    new.save()
    new = Observable(name="Reservoir States")
    new.save()
    new = Observable(name="Input")
    new.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0013_auto_20190327_1837'),
    ]

    operations = [
        migrations.RunPython(populate_observables)
    ]
