# Generated by Django 2.1.7 on 2019-03-27 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0014_auto_20190327_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='lr',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Leaking rate'),
        ),
    ]
