# Generated by Django 2.1.7 on 2019-03-27 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0015_template_lr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='lr',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='Leaking rate'),
        ),
    ]
