# Generated by Django 2.1.7 on 2019-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0016_auto_20190328_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='path',
            field=models.CharField(default='None', max_length=300000),
        ),
    ]
