# Generated by Django 2.1.5 on 2019-03-29 09:47

from django.db import migrations


def network_test(apps, schema_editor):
    Network = apps.get_model('ARNN', 'Network')
    new = Network(id='0', name='nettest', creation_date='2019-03-28 17:20', owner_id='0', template_id='0')
    new.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0018_auto_20190329_0943'),
    ]

    operations = [
        migrations.RunPython(network_test)
    ]
