# Generated by Django 2.1.7 on 2019-04-01 16:08

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import User
import numpy as np
from ..models import Corpus
# from django.shortcuts import get_object_or_404
import os

class Use(User):
    normalize_username = settings.SHARED_CORPUS_ACCOUNT

def populate_observables(apps, schema_editor):
    Observable = apps.get_model('ARNN', 'Observable')
    Observable.objects.filter(name="Rmse"). delete()
    Observable.objects.filter(name="Mse"). delete()
    Observable.objects.filter(name="Nmrse maxmin"). delete()
    Observable.objects.filter(name="Nmrse mean"). delete()
    Observable = apps.get_model('ARNN', 'Observable')
    new = User.objects.create_user(settings.SHARED_CORPUS_ACCOUNT, settings.SHARED_CORPUS_EMAIL, settings.SHARED_CORPUS_ACCOUNT, last_login="2000-01-01 00:00")
    new.save()
    user_path = os.path.join(settings.PATH_TO_USERS_FOLDER, new.username)
    os.mkdir(user_path)
    os.mkdir(os.path.join(user_path, settings.PATH_TO_NETWORKS))
    os.mkdir(os.path.join(user_path, settings.PATH_TO_CORPUS))
    dataname = os.path.join(os.path.join(user_path, settings.PATH_TO_CORPUS), "MackeyGlass")
    data = np.loadtxt('ARNN/reservoirpy/MackeyGlass_t17.txt')
    np.save( dataname +"_in.npy", np.array([[i] for i in data[0:-1]]))
    np.save( dataname +"_out.npy", np.array([[i] for i in data[1:]]))
    corp = Corpus.objects.create(name ="MackeyGlass",size=9999, dim_out=1, dim_in=1, path= dataname, owner = new) 
    corp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0021_auto_20190329_1702'),
    ]

    operations = [
        migrations.RunPython(populate_observables)
    ]
