# Generated by Django 2.1.7 on 2019-04-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARNN', '0023_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='data_in',
            field=models.FileField(default='None', upload_to='', verbose_name='Input file (must be CSV or NPY)'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='data_out',
            field=models.FileField(default='None', upload_to='', verbose_name='Output file (must be CSV or NPY)'),
        ),
    ]
